### ISSUE TITLE
Get rid of catkin warning if possible

### ISSUE THREAD

**Issue by bit-pirate** [stonier/ecl_manipulation#3]
When compiling with catkin:

```
WARNING: Metapackage "ecl" must buildtool_depend on catkin.
```

**Comment by bit-pirate** [comment]
Did you re-release ecl_manipulation?

**Comment by stonier** [comment]
No, didn't have any real bugs or feature updates to release. This was just cosmetic, so waiting for the win-porting to finish before releasing again.
